name: Build and Release mdBook PDF

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
    tags:
      - 'v*' # Trigger on tags like v1.0, v1.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PDF with mdBook-PDF Docker
        run: docker run --rm -v ${{ github.workspace }}:/book hollowman6/mdbook-pdf

      - name: Find generated PDF file
        id: find_pdf
        run: |
          # PDF 파일이 'book/pdf/output.pdf' 경로에 생성될 것이므로 해당 경로를 명시합니다.
          PDF_FILE="book/pdf/output.pdf"
          if [ ! -f "$PDF_FILE" ]; then # 파일이 존재하는지 확인합니다.
            echo "Error: The PDF file '$PDF_FILE' was not found!"
            exit 1
          fi
          echo "pdf_path=$PDF_FILE" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_pdf.outputs.pdf_path }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
